"""Synthetic fixtures for dropout_recovery.py's pure functions, plus a small
real-data structural check (2 clips, like test_sweep_thresholds.py) -- the
full 39-clip report is generated by running the module directly
(`python calibration/dropout_recovery.py`), not on every test run.
"""

import os

from adapter.ingest import ClipData
from adapter.types import Detection, Tag, Track
from calibration.dropout_recovery import (
    MIN_CONTEXT_FRAMES,
    MaskPlacement,
    _center_distance,
    _iou,
    _mask_detections,
    _real_runs,
    _select_placements,
    aggregate,
    aggregate_by_job,
    evaluate_clip,
    run_full_report,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
CLIP_IDS = ["0c54a47b_t010", "407258cd_t036"]


def _det(frame, xyxy=(0.0, 0.0, 40.0, 40.0), tag=Tag.REPORTED):
    return Detection(frame=frame, xyxy=xyxy, confidence=0.8, tag=tag)


# --- pure-function unit tests -----------------------------------------------


def test_iou_identical_boxes_is_one():
    box = (10.0, 10.0, 50.0, 50.0)
    assert _iou(box, box) == 1.0


def test_iou_disjoint_boxes_is_zero():
    assert _iou((0.0, 0.0, 10.0, 10.0), (100.0, 100.0, 110.0, 110.0)) == 0.0


def test_center_distance_zero_for_identical_boxes():
    box = (0.0, 0.0, 40.0, 40.0)
    assert _center_distance(box, box) == 0.0


def test_center_distance_matches_known_offset():
    a = (0.0, 0.0, 40.0, 40.0)  # center (20, 20)
    b = (30.0, 0.0, 70.0, 40.0)  # center (50, 20), 30px to the right
    assert _center_distance(a, b) == 30.0


def test_real_runs_breaks_on_rejected_tag():
    track = Track(track_id=0, detections=[_det(0), _det(1), _det(2, tag=Tag.REJECTED), _det(3), _det(4)])
    runs = _real_runs(track)
    assert [d.frame for d in runs[0]] == [0, 1]
    assert [d.frame for d in runs[1]] == [3, 4]


def test_real_runs_breaks_on_merged_tag():
    """MERGED frames are deliberately excluded from maskable runs -- see the
    module docstring: a suppressed duplicate could resurface if only the
    merge winner is deleted, silently defeating the mask.
    """
    track = Track(track_id=0, detections=[_det(0), _det(1, tag=Tag.MERGED), _det(2)])
    runs = _real_runs(track)
    assert runs == []  # no run of length > 1 survives the break


def test_real_runs_breaks_on_frame_gap():
    track = Track(track_id=0, detections=[_det(0), _det(1), _det(5), _det(6)])
    runs = _real_runs(track)
    assert [d.frame for d in runs[0]] == [0, 1]
    assert [d.frame for d in runs[1]] == [5, 6]


def test_real_runs_ignores_single_frame_islands():
    track = Track(track_id=0, detections=[_det(0), _det(5), _det(10)])
    assert _real_runs(track) == []


def test_select_placements_centers_the_masked_block():
    needed = 3 + 2 * MIN_CONTEXT_FRAMES  # gap_length=3
    frames = list(range(needed))
    track = Track(track_id=0, detections=[_det(f) for f in frames])

    placements = _select_placements([track], gap_length=3)

    assert len(placements) == 1
    p = placements[0]
    assert len(p.frames) == 3
    assert p.frames == sorted(p.frames)
    # real context of at least MIN_CONTEXT_FRAMES on both sides
    assert p.frames[0] - MIN_CONTEXT_FRAMES >= 0
    assert p.pre_frame == p.frames[0] - 1
    assert len(p.context_frames) == 2 * MIN_CONTEXT_FRAMES


def test_select_placements_skips_runs_too_short():
    too_short = 3 + 2 * MIN_CONTEXT_FRAMES - 1
    track = Track(track_id=0, detections=[_det(f) for f in range(too_short)])
    assert _select_placements([track], gap_length=3) == []


def test_mask_detections_removes_exactly_the_masked_boxes():
    xyxy = (5.0, 5.0, 45.0, 45.0)
    other = (500.0, 500.0, 540.0, 540.0)
    clip = ClipData(
        detections=[[Detection(frame=0, xyxy=xyxy, confidence=0.9)], [Detection(frame=1, xyxy=other, confidence=0.9)]],
        frame_ts={0: 0, 1: 1},
        pose=[],
        meta={},
    )
    placement = MaskPlacement(
        gap_length=1, frames=[0], pre_frame=-1, pre_xyxy=(0, 0, 0, 0), removed_boxes={0: xyxy}, context_frames=[]
    )

    _mask_detections(clip, [placement])

    assert clip.detections[0] == []
    assert len(clip.detections[1]) == 1  # untouched frame/box left alone


# --- real-data structural checks (small clip subset, like sweep_thresholds) -


def test_evaluate_clip_returns_job_and_all_gap_lengths():
    result = evaluate_clip(os.path.join(DATA_DIR, "0c54a47b_t010"), gap_lengths=(1, 5))

    assert result["clip_id"] == "0c54a47b_t010"
    assert result["job"] == "Hair stylist"
    assert set(result["by_gap"]) == {1, 5}
    for acc in result["by_gap"].values():
        assert acc["n_frames_masked"] >= acc["n_recovered"]
        assert acc["n_context_checked"] >= acc["n_false_fill"]


def test_evaluate_clip_finds_real_placements_on_a_real_clip():
    """t010 has plenty of short continuous real-detection runs -- a
    short gap length should find at least one maskable placement.
    """
    result = evaluate_clip(os.path.join(DATA_DIR, "0c54a47b_t010"), gap_lengths=(1,))
    assert result["by_gap"][1]["n_placements"] > 0


def test_evaluate_clip_does_not_leak_tags_across_gap_lengths():
    """Each gap length gets its own fresh `load_clip()` -- if that ever broke
    and Detection objects/tags leaked between runs, an earlier gap length's
    interpolated fills could contaminate a later one's placement selection
    or scoring. Rerunning the same clip/gap-length pair twice must be
    deterministic.
    """
    r1 = evaluate_clip(os.path.join(DATA_DIR, "407258cd_t036"), gap_lengths=(3,))
    r2 = evaluate_clip(os.path.join(DATA_DIR, "407258cd_t036"), gap_lengths=(3,))
    assert r1["by_gap"][3]["n_placements"] == r2["by_gap"][3]["n_placements"]
    assert r1["by_gap"][3]["n_recovered"] == r2["by_gap"][3]["n_recovered"]


def test_recovered_localization_error_is_bounded():
    """Every recovered detection's IoU must be a valid ratio and its center
    distance non-negative -- a loose sanity check on the metric computation
    itself, not a claim about pipeline quality.
    """
    result = evaluate_clip(os.path.join(DATA_DIR, "0c54a47b_t010"), gap_lengths=(1, 2, 3))
    for acc in result["by_gap"].values():
        assert all(0.0 <= v <= 1.0 for v in acc["ious"])
        assert all(v >= 0.0 for v in acc["center_dists"])


def test_aggregate_pools_counts_across_clips():
    results = [evaluate_clip(os.path.join(DATA_DIR, cid), gap_lengths=(1, 5)) for cid in CLIP_IDS]
    agg = aggregate(results)

    assert agg["n_clips"] == 2
    total_masked = sum(r["by_gap"][1]["n_frames_masked"] for r in results)
    assert agg["by_gap"][1]["n_frames_masked"] == total_masked


def test_aggregate_by_job_groups_by_meta_job_field():
    results = [evaluate_clip(os.path.join(DATA_DIR, cid), gap_lengths=(1,)) for cid in CLIP_IDS]
    by_job = aggregate_by_job(results)

    assert "Hair stylist" in by_job
    assert "Carpenter" in by_job
    assert by_job["Hair stylist"]["n_clips"] == 1


def test_run_full_report_covers_requested_clips():
    report = run_full_report(DATA_DIR, CLIP_IDS, gap_lengths=(1, 5))

    assert len(report["per_clip"]) == 2
    assert {c["clip_id"] for c in report["per_clip"]} == set(CLIP_IDS)
    assert report["overall"]["n_clips"] == 2
    assert set(report["by_job"]) == {"Hair stylist", "Carpenter"}
