"""Ablation/sensitivity tooling (`calibration/ablation.py`) -- structural
checks against a small clip subset (fast), same pattern as
`test_sweep_thresholds.py`. The full 39-clip report is generated by running
the module directly (`python calibration/ablation.py`), not on every test run.

Every test that compares two configs loads a FRESH `ClipData` for each one
(`_classify` below always calls `load_clip` itself) -- reusing `Detection`
objects across configs would silently carry stage tags forward from the
first run, per this codebase's own documented gotcha (see
`calibration/ablation.py`'s module docstring and `EVAL_LOG.md`).
"""

import os

from adapter.hand_config import hand_config
from adapter.ingest import load_clip
from calibration.ablation import (
    ABLATIONS,
    OUTCOME_KEYS,
    SCALAR_SWEEPS,
    TUPLE_SWEEPS,
    classify_clip,
    outcome_summary,
    run_ablation_suite,
    run_dataset,
    run_sensitivity_suite,
)
from calibration.sweep_thresholds import discover_clip_ids

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
CLIP_IDS = ["0c54a47b_t010", "407258cd_t036"]


def _classify(cid, config):
    clip = load_clip(os.path.join(DATA_DIR, cid))
    return classify_clip(clip, config)


def _raw_and_fabricated_total(cid, config):
    """Independent recomputation of the true total (raw + fabricated),
    deliberately not calling `classify_clip`, mirroring
    `test_sweep_thresholds.py`'s equivalent cross-check.
    """
    from adapter.association import track_detections
    from adapter.geometric import apply_stage1
    from adapter.interpolation import apply_stage4
    from adapter.temporal import apply_stage3

    clip = load_clip(os.path.join(DATA_DIR, cid))
    raw_total = sum(len(dets) for dets in clip.detections)
    stage1_frames = [apply_stage1(list(d), config) for d in clip.detections]
    tracks = track_detections(stage1_frames, config)
    before = sum(len(t.detections) for t in tracks)
    apply_stage3(tracks, clip.pose, config)
    apply_stage4(tracks, config, frame_count=len(clip.detections))
    after = sum(len(t.detections) for t in tracks)
    return raw_total + (after - before)


def test_classify_clip_accounts_for_every_detection():
    config = hand_config()
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert sum(counts.values()) == _raw_and_fabricated_total(cid, config)
        assert all(n >= 0 for n in counts.values())


def test_classify_clip_only_uses_known_outcome_keys():
    config = hand_config()
    counts = _classify(CLIP_IDS[0], config)
    assert set(counts.keys()) <= set(OUTCOME_KEYS)


def test_no_dedup_ablation_eliminates_dropped_duplicate_bucket():
    config = hand_config(**ABLATIONS["no_dedup"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("dropped_duplicate", 0) == 0


def test_no_size_filter_ablation_eliminates_rejected_size_bucket():
    config = hand_config(**ABLATIONS["no_size_filter"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_size", 0) == 0


def test_no_shape_filter_ablation_eliminates_rejected_shape_bucket():
    config = hand_config(**ABLATIONS["no_shape_filter"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_shape", 0) == 0


def test_no_displacement_check_ablation_eliminates_rejected_displacement_bucket():
    config = hand_config(**ABLATIONS["no_displacement_check"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_displacement", 0) == 0


def test_no_flicker_check_ablation_eliminates_rejected_unsupported_bucket():
    config = hand_config(**ABLATIONS["no_flicker_check"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_unsupported", 0) == 0


def test_no_static_check_ablation_eliminates_rejected_static_bucket():
    config = hand_config(**ABLATIONS["no_static_check"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_static", 0) == 0


def test_no_interpolation_ablation_eliminates_interpolated_bucket():
    config = hand_config(**ABLATIONS["no_interpolation"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("interpolated", 0) == 0


def test_no_selection_cap_ablation_eliminates_rejected_selection_bucket():
    config = hand_config(**ABLATIONS["no_selection_cap"])
    for cid in CLIP_IDS:
        counts = _classify(cid, config)
        assert counts.get("rejected_selection", 0) == 0


def test_run_dataset_matches_manual_sum_across_clips():
    config = hand_config()
    manual = sum((_classify(cid, config) for cid in CLIP_IDS), start=__import__("collections").Counter())
    result = run_dataset(DATA_DIR, CLIP_IDS, config)
    assert result == manual


def test_run_ablation_suite_includes_baseline_and_every_ablation():
    results = run_ablation_suite(DATA_DIR, CLIP_IDS)
    assert "full_pipeline" in results
    assert set(ABLATIONS) <= set(results)
    for summary in results.values():
        assert summary["total"] > 0
        assert abs(sum(summary["pct"].values()) - 1.0) < 1e-9


def test_outcome_summary_percentages_sum_to_one():
    config = hand_config()
    counts = run_dataset(DATA_DIR, CLIP_IDS, config)
    summary = outcome_summary(counts)
    assert abs(sum(summary["pct"].values()) - 1.0) < 1e-9


def test_sensitivity_suite_covers_every_declared_param_and_sweeps_fresh_clips():
    # Small ranges only, to keep this test fast -- the real sweep ranges are
    # exercised by running calibration/ablation.py directly.
    from calibration import ablation as ablation_module

    original_scalar = ablation_module.SCALAR_SWEEPS
    original_tuple = ablation_module.TUPLE_SWEEPS
    try:
        ablation_module.SCALAR_SWEEPS = {"max_speed_px_per_frame": [50.0, 110.0, 500.0]}
        ablation_module.TUPLE_SWEEPS = {("plausible_size", "lo"): [0.0, 50.0, 300.0]}
        results = run_sensitivity_suite(DATA_DIR, CLIP_IDS)
    finally:
        ablation_module.SCALAR_SWEEPS = original_scalar
        ablation_module.TUPLE_SWEEPS = original_tuple

    assert set(results) == {"max_speed_px_per_frame", "plausible_size.lo"}
    for series in results.values():
        points = series["points"]
        assert len(points) == 3
        assert any(p["is_default"] for p in points)
        for p in points:
            pct = p["outcome"]["pct"]
            assert abs(sum(pct.values()) - 1.0) < 1e-9
            assert 0.0 <= pct["kept"] <= 1.0
            assert 0.0 <= pct["interpolated"] <= 1.0
        verdict = series["verdict"]
        assert verdict["kept_pct_range"][0] <= verdict["kept_pct_range"][1]


def test_scalar_and_tuple_sweep_ranges_include_the_hand_config_default():
    defaults = hand_config()
    for param, values in SCALAR_SWEEPS.items():
        assert getattr(defaults, param) in values, f"{param} default not in its own sweep range"
    for (param, side), values in TUPLE_SWEEPS.items():
        lo, hi = getattr(defaults, param)
        default = lo if side == "lo" else hi
        assert default in values, f"{param}.{side} default not in its own sweep range"


def test_discover_clip_ids_still_finds_all_39():
    assert len(discover_clip_ids(DATA_DIR)) == 39
