"""Synthetic fixtures for track_quality.py's pure functions, plus a small
real-data structural check (2 clips, like test_sweep_thresholds.py) -- the
full 39-clip report is generated by running the module directly
(`python calibration/track_quality.py`), not on every test run.
"""

import os

from adapter.types import Detection, Tag, Track
from calibration.track_quality import (
    aggregate,
    aggregate_by_job,
    compare_clip,
    fragmentation_candidates,
    gaps_for_track,
    run_full_report,
    summarize_tracks,
    track_length_frames,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
CLIP_IDS = ["0c54a47b_t010", "407258cd_t036"]


def _det(frame, xyxy=(0.0, 0.0, 40.0, 40.0), tag=Tag.REPORTED):
    return Detection(frame=frame, xyxy=xyxy, confidence=0.8, tag=tag)


def _track(track_id, frames, xyxy=(0.0, 0.0, 40.0, 40.0)):
    return Track(track_id=track_id, detections=[_det(f, xyxy) for f in frames])


def test_track_length_frames_counts_gap_frames():
    t = _track(0, [0, 1, 5])  # last - first + 1 = 6, regardless of the gap
    assert track_length_frames(t) == 6


def test_track_length_frames_empty_track_is_zero():
    assert track_length_frames(Track(track_id=0)) == 0


def test_gaps_for_track_finds_internal_gaps_only():
    t = _track(0, [0, 1, 5, 6, 10])
    assert gaps_for_track(t) == [3, 3]  # frames 2-4 missing, then 7-9


def test_gaps_for_track_no_gaps_when_contiguous():
    assert gaps_for_track(_track(0, [0, 1, 2, 3])) == []


def test_fragmentation_candidates_flags_a_close_split():
    """Track B ends at (100, 100) on frame 10; track A starts 5 frames later
    a few pixels away -- well within the box-diagonal-scaled threshold.
    """
    track_b = _track(0, [0, 10], xyxy=(80.0, 80.0, 120.0, 120.0))  # 40x40 box, diag ~56.6
    track_a = _track(1, [15, 20], xyxy=(85.0, 85.0, 125.0, 125.0))  # starts ~7px away

    candidates = fragmentation_candidates([track_b, track_a])

    assert len(candidates) == 1
    b_id, a_id, dt, distance = candidates[0]
    assert (b_id, a_id) == (0, 1)
    assert dt == 5


def test_fragmentation_candidates_ignores_far_apart_tracks():
    track_b = _track(0, [0, 10], xyxy=(0.0, 0.0, 40.0, 40.0))
    track_a = _track(1, [15, 20], xyxy=(900.0, 900.0, 940.0, 940.0))  # far away

    assert fragmentation_candidates([track_b, track_a]) == []


def test_fragmentation_candidates_ignores_wide_time_gaps():
    track_b = _track(0, [0, 10], xyxy=(0.0, 0.0, 40.0, 40.0))
    track_a = _track(1, [500, 505], xyxy=(2.0, 2.0, 42.0, 42.0))  # close, but way later

    assert fragmentation_candidates([track_b, track_a], time_window_frames=30) == []


def test_fragmentation_candidates_ignores_overlapping_tracks():
    """Two tracks alive at the same time (B hasn't ended before A starts)
    aren't a "split of one object" candidate.
    """
    track_b = _track(0, [0, 20], xyxy=(0.0, 0.0, 40.0, 40.0))
    track_a = _track(1, [10, 30], xyxy=(2.0, 2.0, 42.0, 42.0))

    assert fragmentation_candidates([track_b, track_a]) == []


def test_summarize_tracks_basic_shape():
    tracks = [_track(0, [0, 1, 5]), _track(1, [10, 11])]
    summary = summarize_tracks(tracks)

    assert summary["n_tracks"] == 2
    assert summary["track_length_frames"]["mean"] > 0
    assert summary["detections_per_track"]["mean"] > 0
    assert summary["n_gaps"] == 1
    assert summary["total_gap_frames"] == 3
    assert 0.0 <= summary["fragmentation_rate"] <= 1.0
    assert summary["interpolated_proportion"] == 0.0


def test_summarize_tracks_empty_is_all_zero():
    summary = summarize_tracks([])
    assert summary["n_tracks"] == 0
    assert summary["total_gap_frames"] == 0
    assert summary["fragmentation_rate"] == 0.0
    assert summary["interpolated_proportion"] == 0.0


def test_summarize_tracks_ignores_tracks_with_no_detections():
    summary = summarize_tracks([Track(track_id=0), _track(1, [0, 1])])
    assert summary["n_tracks"] == 1


# --- Real-data structural checks (small clip subset, like sweep_thresholds) ---


def test_compare_clip_returns_both_arms_and_job():
    result = compare_clip(os.path.join(DATA_DIR, "0c54a47b_t010"))

    assert result["clip_id"] == "0c54a47b_t010"
    assert result["job"] == "Hair stylist"
    assert result["association_only"]["n_tracks"] > 0
    assert result["full_pipeline"]["n_tracks"] > 0


def test_full_pipeline_arm_can_have_nonzero_interpolated_proportion():
    """The association-only arm never runs stage 4, so it must be exactly
    0.0 -- but the full pipeline does run it, so it need not be.
    """
    result = compare_clip(os.path.join(DATA_DIR, "0c54a47b_t010"))

    assert result["association_only"]["interpolated_proportion"] == 0.0
    assert result["full_pipeline"]["interpolated_proportion"] >= 0.0


def test_compare_clip_does_not_leak_tags_across_arms():
    """The two arms must come from independently loaded clips -- if
    Detection.tag mutation ever leaked across them, the association-only
    arm (which never runs stage 4/5) could show interpolated detections.
    """
    result = compare_clip(os.path.join(DATA_DIR, "407258cd_t036"))
    assert result["association_only"]["interpolated_proportion"] == 0.0


def test_aggregate_pools_across_clips():
    results = [compare_clip(os.path.join(DATA_DIR, cid)) for cid in CLIP_IDS]
    agg = aggregate(results)

    assert agg["association_only"]["n_clips"] == 2
    assert agg["full_pipeline"]["n_clips"] == 2
    total_tracks = sum(r["association_only"]["n_tracks"] for r in results)
    assert agg["association_only"]["n_tracks"] == total_tracks


def test_aggregate_by_job_groups_by_meta_job_field():
    results = [compare_clip(os.path.join(DATA_DIR, cid)) for cid in CLIP_IDS]
    by_job = aggregate_by_job(results)

    assert "Hair stylist" in by_job
    assert "Carpenter" in by_job
    assert by_job["Hair stylist"]["association_only"]["n_clips"] == 1


def test_run_full_report_covers_requested_clips():
    report = run_full_report(DATA_DIR, CLIP_IDS)

    assert len(report["per_clip"]) == 2
    assert set(r["clip_id"] for r in report["per_clip"]) == set(CLIP_IDS)
    assert report["overall"]["association_only"]["n_clips"] == 2
    assert set(report["by_job"]) == {"Hair stylist", "Carpenter"}
